events {
  worker_connections 256;
}

http {
  server {
    listen 80;
    server_name acn.ovh www.acn.ovh localhost;

    location ^~ /.well-known/acme-challenge/ {
      root /var/www/html;
      allow all;
    }

    location / {
      return 301 https://$host$request_uri;
    }
  }

  server {
    listen 443 ssl;
    server_name acn.ovh www.acn.ovh localhost;

    ssl_certificate /etc/letsencrypt/live/acn.ovh/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/acn.ovh/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /var/www/html;
    index index.html;

    add_header X-Content-Type-Options "nosniff";
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header Referrer-Policy "strict-origin-when-cross-origin";
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()";
    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload" always;

    location / {
      limit_except GET HEAD OPTIONS {
        deny all;
      }
      try_files $uri $uri.html $uri/ =404;
    }

    location = /CV.pdf {
      add_header Content-Disposition "inline";
    }

    location ~ /.well-known/acme-challenge/ {
      allow all;
    }

    location ~ /\.(?!well-known).* {
      deny all;
    }
  }
}