name: ACN/test

permissions:
  contents: read

on:
  pull_request:
    branches: [ 'master' ]
  push:
    branches: [ 'master' ]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Test Nuxt
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Mount node cache
        uses: actions/cache@v3
        with:
          path: /node_modules
          key: node-{{ hashFiles('./package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Test linting
        run: npm lint
