name: ACN/test

permissions:
  contents: read

on:
  workflow_dispatch: # Allow manual runs.
  pull_request:
    branches: [ 'master' ]
  push:
    branches: [ 'master' ]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Build Nuxt
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Mount yarn cache
        uses: actions/cache@v3
        with:
          path: front/node_modules
          key: node
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Test linting
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
